version: "3.9"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      #- TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - ${HOME}/Docker/Jellyfin/config:/config
      - ${HOME}/Docker/Jellyfin/cache:/cache
      - ${HOME}/Docker/Jellyfin/media:/media
    ports:
      - "8096:8096"
    restart: always
    networks:
      big-net:

networks:
  big-net:
      name: big-net
